<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="oni">
    <xacro:property name="chassis" value="file:///$(find ugv_robots_descriptions)/robots_description/oni/meshes/chassis.dae"/>

    <xacro:property name="base_mass" value="0.8"/>

    <xacro:property name="wheel_radius" value="0.033"/>
    <xacro:property name="wheel_zoff" value="-0.014"/>

    <xacro:macro name="base_link">
        <link name="base_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 -${pi/2}"/>
                <geometry>
                    <mesh filename="${chassis}"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 -${pi/2}"/>
                <geometry>
                    <mesh filename="${chassis}"/>
                </geometry>
            </collision>
            <inertial>
                <mass value="${base_mass}"/>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <inertia ixx="0.0029" ixy="0.0" ixz="0.0" iyy="0.0029" iyz="0.0" izz="0.00533"/>
            </inertial>
        </link>

        <gazebo reference="base_link">
            <mu1>0.01</mu1>
            <mu2>0.01</mu2>
            <kp>1000000.0</kp>
            <kd>100</kd>
        </gazebo>

        <link name="base_footprint"/>

        <joint name="base_footprint_to_base_link" type="fixed">
            <parent link="base_link"/>
            <child link="base_footprint"/>
            <origin xyz="0.0 0.0 ${-wheel_radius - wheel_zoff}" rpy="0 0 0"/>
        </joint>
    </xacro:macro>

    <xacro:base_link/>
</robot>
